project:
  type: website
  output-dir: docs

website:
  title: "DIPALI VASUDEV MESTRY"
  navbar:
    right:
      - href: index.qmd
        text: "HOME"
      - href: Publications.qmd
        text: "PUBLICATIONS"
      - href: activities.qmd
        text: "ACTIVITIES"
      - href: blog.qmd
        text: "BLOG"
        

format:
  html:
    theme: lux
    fontsize: 1.3em
    linestretch: 2.
    css: styles.css
    toc: true



